### ISSUE TITLE
overflow in R_X86_64_PC32 relocation - developing tether

### ISSUE THREAD

**Issue by asmarcz** [quadrupleslap/tether#25] opened 2019-05-06 15:47 UTC
Hi, I wanted to address issue https://github.com/quadrupleslap/tether/issues/24

I took steps to work on a bugfix as described here: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#testing-a-bugfix

However, when I specify my local version of tether (without changing any source code) I get these errors. What should I do to setup my environment? (Ubuntu, 18.04)

```
target/debug/tether_test: Symbol `webkit_context_menu_get_n_items' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `webkit_context_menu_get_item_at_position' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `webkit_context_menu_item_get_stock_action' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `webkit_context_menu_remove' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_init' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_main' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `malloc' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `malloc' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `malloc' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `free' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `free' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `g_idle_add_full' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_main_quit' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_window_new' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_window_get_type' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `g_type_check_instance_cast' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `g_type_check_instance_cast' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `g_type_check_instance_cast' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `g_type_check_instance_cast' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `g_type_check_instance_cast' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `g_type_check_instance_cast' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `g_type_check_instance_cast' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_window_set_default_size' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_widget_get_type' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_widget_get_type' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_widget_get_type' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_widget_get_type' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_widget_set_size_request' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_window_set_decorated' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_window_set_position' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `g_signal_connect_data' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `g_signal_connect_data' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `g_signal_connect_data' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `webkit_web_view_new' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `webkit_web_view_get_type' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `webkit_web_view_get_settings' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `webkit_web_view_get_user_content_manager' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `webkit_settings_set_enable_developer_extras' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `webkit_user_script_new' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `webkit_user_content_manager_register_script_message_handler' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `webkit_user_content_manager_add_script' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_container_get_type' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_container_add' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_widget_grab_focus' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_widget_show_all' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `webkit_javascript_result_get_js_value' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `jsc_value_to_string' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `g_free' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `webkit_web_view_run_javascript' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `webkit_web_view_load_html' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_window_set_title' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_window_present' causes overflow in R_X86_64_PC32 relocation
target/debug/tether_test: Symbol `gtk_window_close' causes overflow in R_X86_64_PC32 relocation
Segmentation fault (core dumped)
```

EDIT: The error happens at runtime after successful compilation.

**Comment by quadrupleslap** [comment] 2019-05-06 16:02
That's scary. Do you know how I could reproduce it?

**Comment by asmarcz** [comment] 2019-05-06 16:24
I just cloned this repository, in a project I specified the local path for cloned tether and used `hello.rs` example. Strange enough, this error doesn't occur when compiling with version from crate.io obtained by cargo.

**Comment by asmarcz** [comment] 2019-05-06 16:33
I just tried on Windows and it fails too. I think it might be related to not having specified library folder correctly. Here is the error message after `cargo run`:
```
 Running `rustc --edition=2018 --crate-name tether D:\projects\tether\src\lib.rs --color always --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=bd9cd73cbdcf6d57 -C extra-filename=-bd9cd73cbdcf6d57 --out-dir D:\projects\rust\tether_test\target\debug\deps -C incremental=D:\projects\rust\tether_test\target\debug\incremental -L dependency=D:\projects\rust\tether_test\target\debug\deps --extern log=D:\projects\rust\tether_test\target\debug\deps\liblog-a6dff5820c7703a9.rlib -L native=D:\projects\tether\native -l dylib=ole32 -l dylib=user32 -l dylib=windowsapp -l static=tether`
error: could not find native static library `tether`, perhaps an -L flag is missing?

error: aborting due to previous error

error: Could not compile `tether`.
```

**Comment by quadrupleslap** [comment] 2019-05-06 17:08
I think I should follow https://users.rust-lang.org/t/linking-issues-problem-in-link-with-an-object-file-from-c/21673/2?u=quadrupleslap and also get rid of the make dependency.

**Comment by asmarcz** [comment] 2019-05-06 19:12
After updating to 0.3.1, the error happens even with normal dependency `tether = "0.3.1"`

**Comment by quadrupleslap** [comment] 2019-05-06 19:40
Does it fail on Windows, too?

**Comment by asmarcz** [comment] 2019-05-07 15:15
Great, works on Linux now, however on Windows it still doesn't compile.. :/

```
Running `rustc --edition=2018 --crate-name tether D:\Users\asmar\.cargo\registry\src\github.com-1ecc6299db9ec823\tether-0.3.2\src\lib.rs --color always --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=f4a22465f713de13 -C extra-filename=-f4a22465f713de13 --out-dir D:\projects\rust\tether_test\target\debug\deps -L dependency=D:\projects\rust\tether_test\target\debug\deps --extern log=D:\projects\rust\tether_test\target\debug\deps\liblog-a6dff5820c7703a9.rlib --cap-lints allow -L native=D:\projects\rust\tether_test\target\debug\build\tether-9efc0bedda7d4d08\out -l dylib=ole32 -l dylib=user32 -l dylib=windowsapp -l static=tether`
error: could not find native static library `tether`, perhaps an -L flag is missing?
```

**Comment by asmarcz** [comment] 2019-05-07 16:54
I find this line suspicious as it uses in previous versions `native_path` instead. However I tried to make the change locally and the same error is presented.

https://github.com/quadrupleslap/tether/blob/ef23cbf7b2b4f917bc0569cc029585dc7be01727/build.rs#L62

**Comment by quadrupleslap** [comment] 2019-05-07 17:56
Hmm... do you see a tether.lib in the output directory (target/debug/something)? Windows should be able to automatically pick that up, so my guess is that it just doesn't exist.

**Comment by asmarcz** [comment] 2019-05-07 18:11
No, there isn't any.

**Comment by quadrupleslap** [comment] 2019-05-07 18:19
So it looks like the offending part is definitely (https://github.com/quadrupleslap/tether/blob/master/build.rs#L49-L52). If you run

```batch
set OUT_DIR="%CD%"
clang-cl /c /EHsc /std:c++17 /W4 /Wx /Fo"%OUT_DIR%\tether.obj" winapi.cpp
lib /out:"%OUT_DIR%\tether.lib" "%OUT_DIR%\tether.obj"
```

inside the "native" directory, does it make a tether.lib in the current directory?

**Comment by asmarcz** [comment] 2019-05-07 18:45
I suppose you meant inside the cloned tether repository. It gives me:
```
D:\projects\tether\native>clang-cl /c /EHsc /std:c++17 /W4 /Wx /Fo"%OUT_DIR%\tether.obj" winapi.cpp
clang-cl: error: no such file or directory: '/Wx'
```

**Comment by quadrupleslap** [comment] 2019-05-07 18:50
Yeah, in `tether/native` in the cloned repository, using cmd.exe.

**Comment by asmarcz** [comment] 2019-05-07 18:51
That is what I did.

I tried to remove `/Wx` and replaced `out_path` with `native_path` and it runs.

**Comment by asmarcz** [comment] 2019-05-07 18:54
I can maybe submit a pull request if it is OK not to "Treat warnings as errors" in this case as I am don't know what might cause such issue.

**Comment by quadrupleslap** [comment] 2019-05-07 18:55
I'm not sure, but I think Wx might need to be WX.

**Comment by asmarcz** [comment] 2019-05-07 18:56
Yes, it works with `/WX` and `native_path`, great. :)

**Comment by asmarcz** [comment] 2019-05-07 19:00
Yeah, but it doesn't work with the `out_path` unfortunately..

**Comment by quadrupleslap** [comment] 2019-05-07 20:02
Okay so if I understand correctly, the script

```batch
            clang-cl /c /EHsc /std:c++17 /W4 /Wx /Fo"%OUT_DIR%\tether.obj" winapi.cpp
            lib /out:"%OUT_DIR%\tether.lib" "%OUT_DIR%\tether.obj"
```

is still building things in native_path, not out_path. Does that mean `%OUT_DIR%` is not defined?

**Comment by asmarcz** [comment] 2019-05-08 07:09
Heh, I found out that when I
1. manually run inside repository native directory:
```
set OUT_DIR="%CD%"
clang-cl /c /EHsc /std:c++17 /W4 /WX /Fo"%OUT_DIR%\tether.obj" winapi.cpp
lib /out:"%OUT_DIR%\tether.lib" "%OUT_DIR%\tether.obj"
```
2. change to `println!("cargo:rustc-link-search=native={}", native_path.display());`
3. build project using local repository

it works.

Without manual build of the library the build fails. So it seems like tether.lib and/or tether.obj are not saved correctly as they are not present anywhere in the target directory.

However I checked `out_path` variable and it holds seemingly correct: `D:\projects\rust\tether_test\target\debug\build\tether-fe9796ef9695b13a\out`

**Comment by asmarcz** [comment] 2019-05-08 07:31
After bit of investigation I am afraid that `run_script` is never executed.

```
} else if cfg!(target_os = "windows") {
        println!("Is this working?");
        run_script(r#"
            echo "hello" > D:\projects\test.txt
            clang-cl /c /EHsc /std:c++17 /W4 /Fo"%OUT_DIR%\tether.obj" winapi.cpp
            lib /out:"%OUT_DIR%\tether.lib" "%OUT_DIR%\tether.obj"
        "#)?;
    }
```

This prints "Is this working?", however the test.txt file is never created.

**Comment by asmarcz** [comment] 2019-05-09 15:42
I have made some progress.

I found out that CMD doesn't really support multiline commands. So I changed it to:
```
run_script(r#"clang-cl /c /EHsc /std:c++17 /W4 /WX /Fo"%OUT_DIR%\tether.obj" winapi.cpp"#)?;
run_script(r#"lib /out:"%OUT_DIR%\tether.lib" "%OUT_DIR%\tether.obj""#)?;
```

Now, this finally runs clang, however clang dies with:
```
error: unable to open output file '"D:\projects\rust\tether_test\target\debug\build\tether-fe9796ef9695b13a\out\tether.obj"': 'invalid argument'
```

Can't figure out why at the moment.

**Comment by quadrupleslap** [comment] 2019-05-17 05:22
@mcgoo rewrote that bit to use `cc-rs`, so it should work now.

**Comment by quadrupleslap** [comment] 2019-05-23 09:23
Closing because it seems to be fixed.

**Closed by quadrupleslap** 2019-05-23 09:23 UTC
